[project]
src = "src"
dot_env = ".env"

[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = false
prompt_live = false
default_account_name = "Anvil1"
unsafe_password_file = "$HOME/.moccasin/unsafe-passwords/Anvil1"

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "Sepolia1"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.sepolia-zksync]
url = "$ZKSYNC_SEPOLIA_RPC_URL"
chain_id = 300
save_to_db = false
default_account_name = "Sepolia1"
explorer_uri = "https://explorer.sepolia.era.zksync.dev/"
explorer_type = "zksyncexplorer"
is_zksync = true

[networks.sepolia-tenderly]
url = "$TENDERLY_SEPOLIA_RPC_URL"
chain_id = 111551115
save_to_db = false
default_account_name = "Sepolia1"


# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
